{% set name = "tmep" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0c970c857d9bc35590215d3065ff3b29a0d36ca0e1ba9522a2ee0ab8a7b2854f

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<4.0
    - unidecode >=1.3.7,<2.0.0

test:
  imports:
    - tmep
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Josef-Friedrich/tmep
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Template and Macros Expansion for Path names.
  description: |
    This module implements a string formatter based on the standard PEP 292 string.Template class extended with function calls. Variables, as with string.Template, are indicated with $ and functions are delimited with %.
    This module assumes that everything is Unicode: the template and the substitution values. Bytestrings are not supported. Also, the templates always behave like the safe_substitute method in the standard library: unknown symbols are left intact.
  doc_url: https://tmep.readthedocs.io/
  dev_url: https://github.com/Josef-Friedrich/tmep

extra:
  recipe-maintainers:
    - thewchan
