{% set name = "tmep" %}
{% set version = "2.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8561f0db6281f57bf19519c08102a86e6debea74dae7f263cbbaacf98ddce3db

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry >=1.2.0b1
    - poetry-dynamic-versioning-plugin
    - python >=3.6
  run:
    - python >=3.8
    - unidecode >=1.3.4

test:
  imports:
    - tmep
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Josef-Friedrich/tmep
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Template and Macros Expansion for Path names.
  description: |
    This module implements a string formatter based on the standard PEP 292 string.Template class extended with function calls. Variables, as with string.Template, are indicated with $ and functions are delimited with %.
    This module assumes that everything is Unicode: the template and the substitution values. Bytestrings are not supported. Also, the templates always behave like the safe_substitute method in the standard library: unknown symbols are left intact.
  doc_url: https://tmep.readthedocs.io/
  dev_url: https://github.com/Josef-Friedrich/tmep

extra:
  recipe-maintainers:
    - thewchan
